### ISSUE TITLE
Create an activity from code

### ISSUE THREAD

**Issue by derlaft** [qor/activity#5]
This package seems to lack api for creation an activity from the code.

However, activity seems to be nice to display some automated logs.

Will you accept pull request with implementation of this or should a separate package be created?

**Comment by jinzhu** [comment]
Hi @derlaft 

Yes, this is a nice to have feature (I thought I have added that, but seems I am wrong ;) )

So sure, we are open to accept pull request to add this feature.

(going to close this issue, just open a pull request when it is done)

Thank you.

**Comment by dfang** [comment]
Hi, @derlaft 

from your implementation, how to pass the first parameter (*admin.Context) to CreateActivity

eg. How to create an activity when order state updated by code?
